# verbosty level (default critical):
# debug
# info
# warning
# error
# critical
verbose = "critical"


[repo."project1-v1.0.0"]
	type = "git-local"
	uri = "project1-v1.0.0"

[repo."project1-v1.2.0"]
	type = "git-local"
	uri = "project1-v1.2.0"

[repo."project2-v1.3.2"]
	type = "git-local"
	uri = "project2-v1.3.2"

[repo."project2-v1.3.4"]
	type = "git-local"
	uri = "project2-v1.3.4"

[repo."project3-v2.0.0"]
	type = "git-local"
	uri = "project3-v2.0.0"
