[project]
	name = "project1"
	description = "test project 1"
	version = "1.0.0" 

	dependencies = [
		"project2:1.0.0"
	]

[packaging]
	include = [
		"folder1",
		"folder2"
	]

[plugin."plugin1:1.0.0"]
	data = "value"
	